name: "Problem Report"
description: "File a problem report"
title: "[PR]: "
body:
  - type: markdown
    attributes:
      value: "Utilize o formulário abaixo para realizar a abertura do Problem Report"
  - type: input
    id: contato
    attributes:
      label: "Informação de contato"
      placeholder: "ex. email@example.com"
    validations:
      required: false
  - type: input
    id: data
    attributes:
      label: "Data de Abertura"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descrição
      placeholder: "Descrição do problema"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Produto
      options:
        - RobotFX 
  - type: input
    id: version_robotfx
    attributes:
      label: Número da versão
    validations:
      required: true
  - type: dropdown
    id: ambiente
    attributes:
      label: Qual ambiente o problema foi encontrado?
      multiple: true
      options:
        - Produção
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      description: |
      "Critico - Impede o uso da plataforma"
      "Não-Crítico - Não impede o uso da plataforma"
      options:
        - Crítico 
        - Não-Crítico
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      multiple: true
      options:
        - Alta
        - Média
        - Baixa
    validations:
      required: true
